apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-clone-app
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests
    repoURL: 'https://github.com/devops-maestro17/e-Commerce-Sentinel.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true