apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone-app
  namespace: dev
  labels:
    app: amazon-clone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon-clone-app
  template:
    metadata:
      labels:
        app: amazon-clone-app
    spec:
      containers:
      - name: amazon-clone-app
        image: containerizeops/amazon-clone:1.3
        ports:
        - containerPort: 3000
