apiVersion: v1
kind: Service
metadata:
  name: amazon-clone-app-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: amazon-clone-app